name: Publish docker Image

on:
    push:
        branches:
            - main
jobs:
    push-to-registry:
        name: Push to docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: CheckOut
              uses: actions/checkout@v4
            #login docker hub
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            #extract data 
            - name: Extract meta information
              id: meta
              uses: docker/metadata-action@v3
              with:
                images: showkatul/github-action-first
            #build and push
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                    context: .
                    file: ./Dockerfile
                    push: true
                    tags: ${{steps.meta.outputs.tags}}
            




